### ISSUE TITLE
"invalid project" error in docker image when trying to compute dense point cloud

### ISSUE THREAD

**Issue by antoinetdr** [cdcseacave/openMVS#1056]
**Describe the bug**
I use openSfM to generate the point cloud and the camera pose, then I use openSfM method to convert it to scene.mvs
Then I build the docker using the  `QUICK_START.sh` script.
Once in the docker I run :  `DensifyPointCloud scene.mvs `

and got the error: 
12:25:48 [App     ] Build date: Dec 10 2019, 20:59:37
12:25:48 [App     ] CPU: Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz (8 cores)
12:25:48 [App     ] RAM: 43.05GB Physical Memory 0B Virtual Memory
12:25:48 [App     ] OS: Linux 5.15.0-82-generic (x86_64)
12:25:48 [App     ] SSE & AVX compatible CPU & OS detected
12:25:48 [App     ] Command line: scene.mvs
12:25:48 [App     ] error: invalid project 

**To Reproduce**

1. `QUICK_START.sh <Path to data >`  where <Path to data> is the path where the images and all the results from OpenSfM are located
2. I move where the file scene.mvs is `cd /working/undistorted/openmvs/` 
3. I run  `DensifyPointCloud scene.mvs `

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 through docker

Let me know if you need further information

**Comment by cdcseacave** [comment]
how did you generate `scene.mvs`?

**Comment by atdrdeterminant** [comment]
I ran `bin/opensfm export_openmvs <Path to data>`

**Comment by cdcseacave** [comment]
possible the exporter in opensfm is not up to date anymore? I never used opensfm; I'll try to make some time and check it out, that is not code I mentain

**Comment by atdrdeterminant** [comment]
From what I understand, OpenSfM uses `Interface.h` in the exporter, I'll try to use the one from your repository and see how it goes

**Comment by cdcseacave** [comment]
pls try, that should fix the problem, assuming the data is correctly filled in the interface

**Comment by atdrdeterminant** [comment]
So I did the change, recompiled openSfM and ran everything including the point cloud generation, but I still got the same error with no more indication of what went wrong

13:48:11 [App     ] Build date: Dec 10 2019, 20:59:37
13:48:11 [App     ] CPU: Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz (8 cores)
13:48:11 [App     ] RAM: 43.05GB Physical Memory 0B Virtual Memory
13:48:11 [App     ] OS: Linux 5.15.0-82-generic (x86_64)
13:48:11 [App     ] SSE & AVX compatible CPU & OS detected
13:48:11 [App     ] Command line: scene.mvs
13:48:11 [App     ] error: invalid project

**Comment by atdrdeterminant** [comment]
I also tried using OpenMVG using their produced scene.mvs and I still get the same error

**Comment by cdcseacave** [comment]
pls share the images and the command lines you used with openMVG

**Comment by atdrdeterminant** [comment]
I've tested with the Sceaux Castle dataset : https://github.com/openMVG/ImageDataset_SceauxCastle

Using OpenMVG I used the command provided in the tuto to run the SfM : 

`python SfM_GlobalPipeline.py [full path image directory] [resulting directory]`

and 

To get scene.mvs I use :

`openMVG_main_openMVG2openMVS -i sfm_data.bin -o scene.mvs -d scene_undistorted_images`

It generates the scene.mvs file that you can find in the attached zip file
[scene.zip](https://github.com/cdcseacave/openMVS/files/12602145/scene.zip)

**Comment by cdcseacave** [comment]
all works fine with the scene.mvs you sent me
![image](https://github.com/cdcseacave/openMVS/assets/2802670/907ff048-483c-4710-880c-0582b2a53cbb)

**Comment by atdrdeterminant** [comment]
Yes I don't think the problem comes from the file. I'll try to build the docker image using the `./buildFromScratch.sh --cuda --workspace /path/where/your/SFM/results/are` command

**Comment by atdrdeterminant** [comment]
Using openSfM + OpenMVS solved the issue. 

Thank you @cdcseacave  for your time !

**Comment by hepeixin123** [comment]
how do you solve it,
robot@robot:~/code/MVS/openMVS_build$ ./bin/DensifyPointCloud -w /home/robot/code/MVS/data2 -i scene.mvs -o test_dense.mvs
19:57:55 [App     ] Build date: May 26 2024, 22:31:03
19:57:55 [App     ] CPU: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 cores)
19:57:55 [App     ] RAM: 31.26GB Physical Memory 11.44GB Virtual Memory
19:57:55 [App     ] OS: Linux 5.4.0-84-generic (x86_64)
19:57:55 [App     ] SSE & AVX compatible CPU & OS detected
19:57:55 [App     ] Command line: -w /home/robot/code/MVS/data2 -i scene.mvs -o test_dense.mvs
19:57:55 [App     ] error: invalid project
I have the same question

**Comment by Nicny** [comment]
> how do you solve it, robot@robot:~/code/MVS/openMVS_build$ ./bin/DensifyPointCloud -w /home/robot/code/MVS/data2 -i scene.mvs -o test_dense.mvs 19:57:55 [App ] Build date: May 26 2024, 22:31:03 19:57:55 [App ] CPU: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 cores) 19:57:55 [App ] RAM: 31.26GB Physical Memory 11.44GB Virtual Memory 19:57:55 [App ] OS: Linux 5.4.0-84-generic (x86_64) 19:57:55 [App ] SSE & AVX compatible CPU & OS detected 19:57:55 [App ] Command line: -w /home/robot/code/MVS/data2 -i scene.mvs -o test_dense.mvs 19:57:55 [App ] error: invalid project I have the same question

i have the same problem, do you solve it?

**Comment by hepeixin123** [comment]
你可以将 -d 2.5 设置- d 4.0

**Comment by hai-bo1017** [comment]
> > how do you solve it, robot@robot:~/code/MVS/openMVS_build$ ./bin/DensifyPointCloud -w /home/robot/code/MVS/data2 -i scene.mvs -o test_dense.mvs 19:57:55 [App ] Build date: May 26 2024, 22:31:03 19:57:55 [App ] CPU: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 cores) 19:57:55 [App ] RAM: 31.26GB Physical Memory 11.44GB Virtual Memory 19:57:55 [App ] OS: Linux 5.4.0-84-generic (x86_64) 19:57:55 [App ] SSE & AVX compatible CPU & OS detected 19:57:55 [App ] Command line: -w /home/robot/code/MVS/data2 -i scene.mvs -o test_dense.mvs 19:57:55 [App ] error: invalid project I have the same question
> 
> i have the same problem, do you solve it?

do you solve it?

**Comment by hai-bo1017** [comment]
> 你可以将 -d 2.5 设置- d 4.0

what's mean?

**Comment by cdcseacave** [comment]
Closing as the original issue was solved. Note that error: invalid project occurs when the specified input .mvs file does not exist in the working directory (e.g. volume mounts in Docker not mapping to the expected paths), is empty (0 bytes), or contains no calibrated images (< 2 images).
